/**
 * Service to handle Darwin Core standard mapping and information.
 */
class DarwinCoreService {
  /**
   * Returns metadata about the Darwin Core fields used in the system.
   */
  getFieldsDefinition() {
    return [
      { term: 'occurrenceID', definition: 'An identifier for the Occurrence (autogenerated UUID).' },
      { term: 'scientificName', definition: 'The full scientific name, with authorship and date information if known.' },
      { term: 'kingdom', definition: 'The full scientific name of the kingdom in which the taxon is classified.' },
      { term: 'phylum', definition: 'The full scientific name of the phylum or division in which the taxon is classified.' },
      { term: 'class', definition: 'The full scientific name of the class in which the taxon is classified.' },
      { term: 'order', definition: 'The full scientific name of the order in which the taxon is classified.' },
      { term: 'family', definition: 'The full scientific name of the family in which the taxon is classified.' },
      { term: 'genus', definition: 'The full scientific name of the genus in which the taxon is classified.' },
      { term: 'specificEpithet', definition: 'The name of the first-level infraspecific epithet of the scientificName.' },
      { term: 'locality', definition: 'The specific description of the place.' },
      { term: 'decimalLatitude', definition: 'The geographic latitude (in decimal degrees).' },
      { term: 'decimalLongitude', definition: 'The geographic longitude (in decimal degrees).' },
      { term: 'eventDate', definition: 'The date-time or interval during which an Event occurred (ISO 8601).' },
      { term: 'recordedBy', definition: 'A list of names of people, groups, or organizations responsible for recording the Occurrence.' }
    ];
  }

  /**
   * Simulates data standardization view.
   */
  getComparisonExample() {
    return {
      before: {
        id: 1,
        name: "espeletia GRANDIFLORA",
        date: "15/11/2023",
        place: "Bogotá, Sumapaz",
        collector: "Helena R."
      },
      after: {
        occurrenceID: "db4e4887-1422-4a00-9883-2fbad0ee55a0",
        scientificName: "Espeletia grandiflora",
        eventDate: "2023-11-15",
        locality: "Páramo de Sumapaz, Cundinamarca, Colombia",
        recordedBy: "Dr. Helena Rodríguez"
      }
    };
  }
}

export default new DarwinCoreService();
