import { supabase } from '../api/supabase';

/**
 * Service to handle data persistence in Supabase (PostgreSQL).
 */
class SpecimenService {
  async getAll() {
    const { data, error } = await supabase
      .from('specimens')
      .select('*')
      .order('createdAt', { ascending: false });

    if (error) {
      console.error('Error fetching specimens:', error);
      return [];
    }
    return data;
  }

  async getById(id) {
    const { data, error } = await supabase
      .from('specimens')
      .select('*')
      .eq('occurrenceID', id)
      .single();

    if (error) {
      console.error('Error fetching specimen by ID:', error);
      return null;
    }
    return data;
  }

  async create(specimen) {
    // Note: occurrenceID and id are auto-generated by Supabase in my SQL script
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('specimens')
      .insert([{
        ...specimen,
        user_id: user?.id,
        createdAt: new Date().toISOString(),
        lastModified: new Date().toISOString()
      }])
      .select()
      .single();

    if (error) {
      console.error('Error creating specimen:', error);
      throw error;
    }
    return data;
  }

  async update(id, specimen) {
    const { data, error } = await supabase
      .from('specimens')
      .update({
        ...specimen,
        lastModified: new Date().toISOString()
      })
      .eq('occurrenceID', id)
      .select()
      .single();

    if (error) {
      console.error('Error updating specimen:', error);
      throw error;
    }
    return data;
  }

  async delete(id) {
    const { error } = await supabase
      .from('specimens')
      .delete()
      .eq('occurrenceID', id);

    if (error) {
      console.error('Error deleting specimen:', error);
      throw error;
    }
    return true;
  }

  async reset() {
    // Resetting for a specific user might involve deleting all and re-inserting defaults
    // For safety, we'll just log this and perhaps clear local state if needed
    console.warn('Reset collection called. In a real DB, this should be handled with care.');
    return [];
  }

  /**
   * Merges imported data with existing data in Supabase.
   */
  async merge(importedData) {
    const { data: { user } } = await supabase.auth.getUser();
    
    const preparedData = importedData.map(item => ({
      ...item,
      user_id: user?.id,
      lastModified: new Date().toISOString()
    }));

    const { data, error } = await supabase
      .from('specimens')
      .upsert(preparedData, { onConflict: 'occurrenceID' })
      .select();

    if (error) {
      console.error('Error merging specimens:', error);
      throw new Error(`Error de base de datos: ${error.message} (${error.code})`);
    }
    return data;
  }
}

export default new SpecimenService();
